const menu = [
    {
      id: 1,
      title: 'Süzme Pankek',
      category: 'breakfast',
      price: 15.99,
      img: './menu-img/item-1.jpeg',
      desc: 'Sütün lezzeti buttermilk pankeklerde! Yumuşacık bir dokuya sahip süzme pankeklerimizle gününüze tat katın.',
    },
    {
      id: 2,
      title: 'Diner ikili hamburger',
      category: 'lunch',
      price: 13.99,
      img: './menu-img/item-2.jpeg',
      desc: 'Diner usulü hazırlanan ikili hamburgerimiz, enfes lezzeti ve doyurucu yapısıyla lunchniz için mükemmel bir tercih!',
    },
    {
      id: 3,
      title: 'Godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: './menu-img/item-3.jpeg',
      desc: 'Efsanevi bir lezzet sizi bekliyor! Godzilla Milkshake imizle kendinizi şımartın ve tatlı bir mola verin.',
    },
    {
      id: 4,
      title: 'Köy lezzeti',
      category: 'breakfast',
      price: 20.99,
      img: './menu-img/item-4.jpeg',
      desc: 'Köy breakfastlarının vazgeçilmez lezzeti artık burada! Tamamen doğal malzemelerle hazırlanan Köy Lezzeti breakfastsı, sizleri enfes bir lezzet şölenine davet ediyor.',
    },
    {
      id: 5,
      title: 'Yumurta saldırısı',
      category: 'lunch',
      price: 22.99,
      img: './menu-img/item-5.jpeg',
      desc: 'Köy breakfastlarının vazgeçilmez lezzeti artık burada! Tamamen doğal malzemelerle hazırlanan Köy Lezzeti breakfastsı, sizleri enfes bir lezzet şölenine davet ediyor.',
    },
  
    {
      id: 6,
      title: 'Oreo Hayali',
      category: 'shakes',
      price: 18.99,
      img: './menu-img/item-6.jpeg',
      desc: 'Oreo sevenler için muhteşem bir lezzet! Oreo Hayali sizi tatlı bir dünyaya götürüyor. Lezzetine doyum olmaz!',
    },
    {
      id: 7,
      title: 'Bacon Seli',
      category: 'breakfast',
      price: 8.99,
      img: './menu-img/item-7.jpeg',
      desc: 'breakfastnın olmazsa olmazı bacon sevenleri için! Bol bol taze kızarmış bacon ve diğer lezzetlerle hazırlanan Bacon Seli, güne harika bir başlangıç yapmanızı sağlayacak.',
    },
    {
      id: 8,
      title: 'Amerikan Klasik',
      category: 'lunch',
      price: 12.99,
      img: './menu-img/item-8.jpeg',
      desc: 'Amerikan mutfağının klasik lezzetleriyle hazırlanan bu lunch, tadına doyum olmayan bir deneyim sunuyor. Üstelik uygun fiyatıyla da tercih sebebi!',
    },
    {
      id: 9,
      title: 'Karantina Arkadaşı',
      category: 'shakes',
      price: 16.99,
      img: './menu-img/item-9.jpeg',
      desc: 'Karantina günlerinde canınızın sıkıldığı anlarda sizi yalnız bırakmayacak lezzetli bir milkshake! Karantina Arkadaşı ile tatlı bir kaçamak yapın.',
    },
    {
      id: 10,
      title: 'Bizon Bifteği',
      category: 'lunch',
      price: 22.99,
      img: './menu-img/item-10.jpeg',
      desc: 'Bizon etinin eşsiz lezzeti, özel baharatlar ve soslarla birleşiyor. Bizon Bifteği, akşam yemeğiniz için mükemmel bir seçim!',
    },
  ];

  export default menu
  